### ISSUE TITLE
Doesn't compile with latest version of ROSJava

### ISSUE THREAD

**Issue by chadrockey** [ros-android/android_sensors_driver#1]
App doesn't compile with ROSJava released in mid-Febuary.  Update to latest and push to Market.

**Comment by axelfurlan** [comment]
Fixed in the pull request version. The code compiles in current rosjava environment (post-gradle shift). A readme file is attached with compiling instructions.

**Comment by chadrockey** [comment]
Fixed via pull request thanks to Axel Furlan!
https://github.com/chadrockey/android_sensors_driver/pull/9
