### ISSUE TITLE
remember recent hosts

### ISSUE THREAD

**Issue by dawonn** [ros-android/android_sensors_driver#16]
I also need to switch between masters, be really useful if I didn't have to type in the IP address every time. I wish that the main screen would list my recently connected masters.

**Comment by chadrockey** [comment]
This part of the app comes from the "Master Chooser" component of upstream ROSJava. Please report this issue there:

https://github.com/rosjava/android_core/issues

**Comment by dawonn** [comment]
https://github.com/rosjava/android_core/issues/193
