### ISSUE TITLE
show connection status

### ISSUE THREAD

**Issue by dawonn** [ros-android/android_sensors_driver#17]
it would be nice if once you hit ok and the server starts, it could show if it actually connected to a master, or if the connection is dropped prompt the user.

**Comment by chadrockey** [comment]
This was already implemented upstream in the MasterChooser:

https://github.com/rosjava/android_core/blob/master/android_10/src/org/ros/android/MasterChooser.java#L195

**Comment by dawonn** [comment]
Does that mean there is a new version of the ROS sensors app on the way to
the app market? :)

“The greater danger for most of us lies not in setting our aim too high and
falling short; but in setting our aim too low, and achieving our mark.” -
Michelangelo
