### ISSUE TITLE
default port address

### ISSUE THREAD

**Issue by dawonn** [ros-android/android_sensors_driver#18]
If the port address is ommited from the connection URL, it would be nice if it automatically used a default of 11311.

I accidentally deleted it without noticing, and spent three hours debugging why it wasn't working.

**Comment by chadrockey** [comment]
This part of the app comes from the "Master Chooser" component of upstream ROSJava.  Please report this issue there:

https://github.com/rosjava/android_core/issues

**Comment by dawonn** [comment]
Thanks again for this application, I have been using it quite a bit recently:) 

https://github.com/rosjava/android_core/issues/192
