### ISSUE TITLE
android_sensors_driver compatible with virtualbox version of ROS?

### ISSUE THREAD

**Issue by musik09** [ros-android/android_sensors_driver#19]
Does the android_sensors_driver work on a virtualbox version of ubuntu running  ROS? I used a tutorial to try to get the android_sensors_driver application working but my attempts have been unsuccessful.

**Comment by chadrockey** [comment]
Virtualbox has pretty difficult to use networking issues that can crop up sometime.  Make sure it's firewall and port forwarding is done correctly.

If it works with normal ROS (bidirectional communication), it should work with android_sensors_driver.

Try using rosnode ping from a laptop to connect to the master running in virtualbox.  If you can get that to work, android sensors driver will work.

In the future, unless there's a specific technical issue, requests for help should be asked on http://answers.ros.org/questions/
